### PR TITLE
Merge the Repository 

### PR DESCRIPTION
**Pull request by RF-UVA**
Request for Merage Repository

### CODE REVIEW

**Comment by RF-UVA** [comment]
Comments

**Comment by RF-UVA** [comment]
comment

**Comment by RF-UVA** [comment]
Comment for merge the Repository

**Comment by RF-UVA** [comment]
Reopen

**Comment by RF-UVA** [comment]
Request for Merage Repository

**Comment by homa-alem** [comment]
You didn't make the change to the students.txt. Please do so, commit, and make a new pull request.

**Pull request merged**
